global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bola_strike_api'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'bola_strike_cli'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8001']
